using ArabicaCliento.Systems;
using ArabicaCliento.UI.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace ArabicaCliento.UI;

[GenerateTypedNameReferences]
public sealed partial class CheatMenuWindow : ArabicaWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    
    private readonly ArabicaDiscordSystem? _arabicaDiscord;

    public CheatMenuWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _arabicaDiscord ??= _entMan.System<ArabicaDiscordSystem>();
        TitleLabel.Text = "ArabicaCliento: Click GUI";
        Ranged.Pressed = ArabicaConfig.RangedAimbotEnabled;
        Melee.Pressed = ArabicaConfig.MeleeAimbotEnabled;
        Autospin.Pressed = ArabicaConfig.SpinBotEnabled;
        Antislip.Pressed = ArabicaConfig.AntiSlipEnabled;
        //LogPlayers.Pressed = ArabicaConfig.LogPlayers;

        SyndicateDetector.Pressed = ArabicaConfig.SyndicateDetector;
        Melee.OnToggled += args => ArabicaConfig.MeleeAimbotEnabled = args.Pressed;
        Ranged.OnToggled += args => ArabicaConfig.RangedAimbotEnabled = args.Pressed;
        Autospin.OnToggled += args => ArabicaConfig.SpinBotEnabled = args.Pressed;
        Antislip.OnToggled += args => ArabicaConfig.AntiSlipEnabled = args.Pressed;
        SyndicateDetector.OnToggled += args => ArabicaConfig.SyndicateDetector = args.Pressed;
        Discord.OnPressed += _ => _arabicaDiscord?.OpenDiscord();
        //LogPlayers.OnToggled += args => ArabicaConfig.LogPlayers = args.Pressed;
    }
}