using ArabicaCliento.UI.Controls;
using Content.Client.Resources;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.XAML;

namespace ArabicaCliento.UI;

[GenerateTypedNameReferences]
public sealed partial class CheatMenuWindow : ArabicaWindow
{
    public CheatMenuWindow()
    {
        RobustXamlLoader.Load(this);
        TitleLabel.Text = "ArabicaCliento: Click GUI";
        Ranged.Pressed = ArabicaConfig.RangedAimbotEnabled;
        Melee.Pressed = ArabicaConfig.MeleeAimbotEnabled;
        Autospin.Pressed = ArabicaConfig.SpinBotEnabled;
        Antislip.Pressed = ArabicaConfig.AntiSlipEnabled;
        //LogPlayers.Pressed = ArabicaConfig.LogPlayers;
        
        SyndicateDetector.Pressed = ArabicaConfig.SyndicateDetector;
        Melee.OnToggled += args => ArabicaConfig.MeleeAimbotEnabled = args.Pressed;
        Ranged.OnToggled += args => ArabicaConfig.RangedAimbotEnabled = args.Pressed;
        Autospin.OnToggled += args => ArabicaConfig.SpinBotEnabled = args.Pressed;
        Antislip.OnToggled += args => ArabicaConfig.AntiSlipEnabled = args.Pressed;
        SyndicateDetector.OnToggled += args => ArabicaConfig.SyndicateDetector = args.Pressed;
        //LogPlayers.OnToggled += args => ArabicaConfig.LogPlayers = args.Pressed;
    }
}